apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reservation
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-reservation
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-reservation
    spec:
      containers:
        - name: reservation
          image: "{{ .Values.image.reservation.repository }}:{{ .Values.image.reservation.tag }}"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
